apiVersion: 1

datasources:
  - name: PostgreSQL Gempa
    uid: gempa-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: gempa
    user: gempa
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
